export { default as TechStack } from './TechStack'
export { default as Intro } from './Intro'
export { default as About } from './About'
export { default as Background } from './Background'
export { default as Projects } from './Projects'
export { default as Socials } from './Socials'
